# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - main

# pool:
#   vmImage: ubuntu-latest
  
# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'


trigger: none
pr: none

pool:
  name: Lab Pool   # seu pool self-hosted (NÃO usar vmImage aqui)

steps:
  - powershell: |
      Write-Host "Agente: $(Agent.Name)"
      Write-Host "Run ID: $(Build.BuildId)"

